[package]
name = "iata_bcbp_ffi"
version = "1.0.0"
authors = ["Martin Mroz <martinmroz@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
iata_bcbp = "1.0"
libc = "0.2"

[build-dependencies]
serde_derive = "=1.0.34"
cbindgen = "0.9"
